### PR TITLE
Fix TM permissions (#32) and add BWAPI 4.4.0 support (#34)

### PR DESCRIPTION
**Pull request by chriscoxe**
**Update 2019-03-24**: the original plan was to add support for BWAPI 4.3.0 and that is how this pull request was originally written, but the plan changed to only add support for BWAPI 4.4.0, not 4.3.0 too. So I have edited this issue to replace references of BWAPI 4.3.0 with just BWAPI 4.4.0 (even though the commit history will show that 4.3.0 was added then 4.4.0 added then 4.3.0 removed).

Changes are included for these issues:
#32
#34

I've included the TournamentModule.dll & JAR files that I compiled, but my bot (ZZZKBot) competed in AIIDE/CIG competitions in the past, so I realize you may want to compile them yourself to ensure they are trustworthy.  You can check that the file checksums of other files like the official BWAPI.dll are correct.

If you use my TournamentModule.dll file for BWAPI 4.2.0 and/or 4.4.0, note that as I mentioned in the commit messages, for BWAPI 4.2.0 I used Microsoft Visual Studio Community 2017 version 15.7.4 (linking with an unpacked and unaltered https://github.com/bwapi/bwapi/releases/download/v4.2.0/BWAPI.VS.15.7.3.7z). For BWAPI 4.4.0 I used Microsoft Visual Studio Community 2017 version 15.9.8 (linking with an unpacked and unaltered https://github.com/bwapi/bwapi/releases/download/v4.4.0/BWAPI.7z although I had to build BWAPILIB.lib myself because the official releases no longer provide it). They are later versions of Visual Studio 2017 than was used to build the official BWAPI 4.2.0, so it may require client machines to have a more recent version of the Microsoft Visual C++ Redistributable for Visual Studio 2017 installed. E.g. can get the latest version from https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads. I haven't tested upgrading the redist though - it worked for me, but that may be because I already had a more recent version installed.  The DLL for 4.1.2 should not need an updated redist.

I built the JARs using jdk-8u201-windows-i586.exe. client.jar needed to be updated. I also pushed the updated server.jar & results_parser.jar but I'm not sure whether I needed to, because I only changed some comments in the src/objects folder.

### CODE REVIEW

**Comment by davechurchill** [comment]
Been kind of busy, just tagging @richard-kelly so he can have a look at this eventually

**Comment by chriscoxe** [comment]
I gather that BWAPI 4.3.0 crashes a lot due to issues relating to the new latency compensation logic, so let's put this pull request on hold until sometime after the next version is released, which I expect will be quite soon, and see how it goes on BASIL and/or SSCAIT first.

**Comment by chriscoxe** [comment]
Update: I've added support for BWAPI 4.4.0 and removed support for BWAPI 4.3.0.  Should be good to go.  Note: BASIL has supported BWAPI 4.4.0 for 10 days now (although I don't know whether any bots are using it) and  SSCAIT doesn't support BWAPI 4.4.0 yet.

**Comment by richard-kelly** [comment]
I tested the new tournament modules and a 4.40 bot in our tournament setup. Thanks @chriscoxe !

**Pull request merged**
