### PR TITLE
Adding option to disable persistent knowledge

### PR DESCRIPTION
**Pull request by andertavares**
Hi, I had the need to remove bots' persistent knowledge from one round to the next so I added this option to the tournament manager.

With persistent knowledge disabled, files in bwapi-data/write are not moved to bwapi-data/read.

Plus, some typos were fixed.

### CODE REVIEW

**Comment by davechurchill** [comment]
I am not currently accepting pull requests on the TM software as I'm quite
busy and don't have time to review the changes and/or test them.

On Mon, Jun 20, 2016 at 2:04 PM, Anderson notifications@github.com wrote:

> Hi, I had the need to remove bots' persistent knowledge from one round to
> the next so I added this option to the tournament manager.
> 
> With persistent knowledge disabled, files in bwapi-data/write are not
> moved to bwapi-data/read.
> 
> ## Plus, some typos were fixed.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/davechurchill/StarcraftAITournamentManager/pull/6
> Commit Summary
> - Adding option to allow 'blind' games, i.e., where bots won't be able
>   to
> - moving log command to condition that executes move write->read action
> - Update README.md
> - fixing a typo and spacing issue
> 
> File Changes
> - _M_ .gitignore
>   https://github.com/davechurchill/StarcraftAITournamentManager/pull/6/files#diff-0
>   (3)
> - _M_ README.md
>   https://github.com/davechurchill/StarcraftAITournamentManager/pull/6/files#diff-1
>   (4)
> - _M_ server/server_settings.ini
>   https://github.com/davechurchill/StarcraftAITournamentManager/pull/6/files#diff-2
>   (9)
> - _M_ src/server/Server.java
>   https://github.com/davechurchill/StarcraftAITournamentManager/pull/6/files#diff-3
>   (15)
> - _M_ src/server/ServerSettings.java
>   https://github.com/davechurchill/StarcraftAITournamentManager/pull/6/files#diff-4
>   (14)
> 
> Patch Links:
> 
>    -
>    https://github.com/davechurchill/StarcraftAITournamentManager/pull/6.patch
>    -
>    https://github.com/davechurchill/StarcraftAITournamentManager/pull/6.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/davechurchill/StarcraftAITournamentManager/pull/6,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABIkqKSDwwRS896M_-6tLeMr9XYA06blks5qNvJTgaJpZM4I6EcN
> .

## 

David Churchill - dave.churchill@gmail.com

PhD, Artificial Intelligence
Computing Science Department, University of Alberta
http://webdocs.cs.ualberta.ca/~cdavid/ cdavid@cs.ualberta.ca

Lead AI Programmer, Lunarch Studios
http://www.lunarchstudios.com/ http://lunarchstudios.com/

**Comment by andertavares** [comment]
Ok, no problem.

**Comment by davechurchill** [comment]
I will probably be doing some small updates to the TM for this year's
competition and I will manually merge in some of these ideas since they do
make sense for those who want those options. Thanks!

On Mon, Jun 20, 2016 at 2:13 PM, Anderson notifications@github.com wrote:

> Closed #6
> https://github.com/davechurchill/StarcraftAITournamentManager/pull/6.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/davechurchill/StarcraftAITournamentManager/pull/6#event-698164396,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABIkqNl1Yr0K3bPaqH03d1FYuRVCH7mrks5qNvRWgaJpZM4I6EcN
> .

## 

David Churchill - dave.churchill@gmail.com

PhD, Artificial Intelligence
Computing Science Department, University of Alberta
http://webdocs.cs.ualberta.ca/~cdavid/ cdavid@cs.ualberta.ca

Lead AI Programmer, Lunarch Studios
http://www.lunarchstudios.com/ http://lunarchstudios.com/

**Comment by andertavares** [comment]
Good! If you need any help, please let me know.

**Pull request closed without merging**
